"""Add match statistics

Revision ID: 0a2ebbf64a39
Revises: 0a52641db111
Create Date: 2022-03-27 22:15:36.564833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2ebbf64a39'
down_revision = '0a52641db111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_statistics',
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('statistic', sa.String(length=3), nullable=False),
        sa.Column('home_team', sa.String(length=100), nullable=False),
        sa.Column('home_stat', sa.Integer(), nullable=True),
        sa.Column('away_stat', sa.Integer(), nullable=True),
        sa.Column('away_team', sa.String(length=100), nullable=False),
        sa.Column('url', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('date', 'statistic', 'home_team'),
        schema='football-data'
    )
    op.create_index('ix_match_statistics_statistic', 'match_statistics', ['statistic'], unique=False, schema='football-data')
    op.create_index('ix_match_statistics_url', 'match_statistics', ['url'], unique=False, schema='football-data')
    op.create_index('uq_match_statistics', 'match_statistics', ['date', 'away_team', 'statistic'], unique=True, schema='football-data')
    op.create_table('statistic',
        sa.Column('code', sa.String(length=3), nullable=False),
        sa.Column('name', sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint('code'),
        sa.UniqueConstraint('name'),
        schema='football-data'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic', schema='football-data')
    op.drop_index('uq_match_statistics', table_name='match_statistics', schema='football-data')
    op.drop_index('ix_football-data_match_statistics_url', table_name='match_statistics', schema='football-data')
    op.drop_index('ix_football-data_match_statistics_statistic', table_name='match_statistics', schema='football-data')
    op.drop_table('match_statistics', schema='football-data')
    # ### end Alembic commands ###
