"""Match table only

Revision ID: 6d8a0adb672f
Revises: 
Create Date: 2022-03-18 15:03:05.403651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8a0adb672f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'match',
        sa.Column('division', sa.String(length=3), nullable=True),
        sa.Column('country', sa.String(length=20), nullable=True),
        sa.Column('league', sa.String(length=100), nullable=True),
        sa.Column('season', sa.String(length=100), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('time', sa.Time(), nullable=True),
        sa.Column('home_team', sa.String(length=50), nullable=False),
        sa.Column('home_goals', sa.Integer(), nullable=True),
        sa.Column('result', sa.String(length=1), nullable=True),
        sa.Column('away_goals', sa.Integer(), nullable=True),
        sa.Column('away_team', sa.String(length=50), nullable=False),
        sa.Column('ht_home_goals', sa.Integer(), nullable=True),
        sa.Column('ht_result', sa.String(length=1), nullable=True),
        sa.Column('ht_away_goals', sa.Integer(), nullable=True),
        sa.Column('referee', sa.String(length=50), nullable=True),
        sa.Column('attendance', sa.Integer(), nullable=True),
        sa.Column('url', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('date', 'home_team'),
        schema='football-data'
    )
    op.create_index('ix_match_url', 'match', ['url'], unique=False, schema='football-data')
    op.create_index('uq_match', 'match', ['date', 'away_team'], unique=True, schema='football-data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_match', table_name='match', schema='football-data')
    op.drop_index('ix_match_url', table_name='match', schema='football-data')
    op.drop_table('match', schema='football-data')
    # ### end Alembic commands ###
