"""Add raw JSON table

Revision ID: c8a2799837ae
Revises: f0bd0902efc3
Create Date: 2022-04-05 09:56:02.230647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a2799837ae'
down_revision = '070e958c019b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw',
        sa.Column('url', sa.String(length=100), nullable=False),
        sa.Column('json', sa.JSON(), nullable=False),
        sa.Column('loaded_at', sa.DateTime(), nullable=False),
        schema='football-data'
    )
    op.create_index('ix_raw_url', 'raw', ['url'], unique=False, schema='football-data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_url', table_name='raw', schema='football-data')
    op.drop_table('raw', schema='football-data')
    # ### end Alembic commands ###
