"""Add betting tables - bookmakers, odds, over/unders and asian handicaps

Revision ID: f0bd0902efc3
Revises: 0a2ebbf64a39
Create Date: 2022-04-02 17:37:14.620931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bd0902efc3'
down_revision = '0a2ebbf64a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmaker',
        sa.Column('code', sa.String(length=5), nullable=False),
        sa.Column('name', sa.String(length=20), nullable=False),
        sa.Column('closing', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('code'),
        schema='football-data'
    )

    op.create_table('match_asian_handicap',
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('bookmaker', sa.String(length=5), nullable=False),
        sa.Column('home_team', sa.String(length=100), nullable=False),
        sa.Column('home', sa.Float(), nullable=False),
        sa.Column('away', sa.Float(), nullable=False),
        sa.Column('away_team', sa.String(length=100), nullable=False),
        sa.Column('handicap', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('count', sa.Integer(), nullable=True),
        sa.Column('url', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('date', 'bookmaker', 'home_team'),
        schema='football-data'
    )
    op.create_index('ix_match_asian_handicap_bookmaker', 'match_asian_handicap', ['bookmaker'], unique=False, schema='football-data')
    op.create_index('ix_match_asian_handicap_url', 'match_asian_handicap', ['url'], unique=False, schema='football-data')
    op.create_index('uq_match_asian_handicap', 'match_asian_handicap', ['date', 'away_team', 'bookmaker'], unique=True, schema='football-data')

    op.create_table('match_odds',
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('bookmaker', sa.String(length=5), nullable=False),
        sa.Column('home_team', sa.String(length=100), nullable=False),
        sa.Column('home', sa.Float(), nullable=False),
        sa.Column('draw', sa.Float(), nullable=False),
        sa.Column('away', sa.Float(), nullable=False),
        sa.Column('away_team', sa.String(length=100), nullable=False),
        sa.Column('count', sa.Integer(), nullable=True),
        sa.Column('url', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('date', 'bookmaker', 'home_team'),
        schema='football-data'
    )
    op.create_index('ix_match_odds_bookmaker', 'match_odds', ['bookmaker'], unique=False, schema='football-data')
    op.create_index('ix_match_odds_url', 'match_odds', ['url'], unique=False, schema='football-data')
    op.create_index('uq_match_odds', 'match_odds', ['date', 'away_team', 'bookmaker'], unique=True, schema='football-data')

    op.create_table('match_over_under',
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('bookmaker', sa.String(length=5), nullable=False),
        sa.Column('home_team', sa.String(length=100), nullable=False),
        sa.Column('away_team', sa.String(length=100), nullable=False),
        sa.Column('over', sa.Float(), nullable=False),
        sa.Column('under', sa.Float(), nullable=False),
        sa.Column('count', sa.Integer(), nullable=True),
        sa.Column('url', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('date', 'bookmaker', 'home_team'),
        schema='football-data'
    )
    op.create_index('ix_match_over_under_bookmaker', 'match_over_under', ['bookmaker'], unique=False, schema='football-data')
    op.create_index('ix_match_over_under_url', 'match_over_under', ['url'], unique=False, schema='football-data')
    op.create_index('uq_match_over_under', 'match_over_under', ['date', 'away_team', 'bookmaker'], unique=True, schema='football-data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_match_over_under', table_name='match_over_under', schema='football-data')
    op.drop_index('ix_match_over_under_url', table_name='match_over_under', schema='football-data')
    op.drop_index('ix_match_over_under_bookmaker', table_name='match_over_under', schema='football-data')
    op.drop_table('match_over_under', schema='football-data')
    op.drop_index('uq_match_odds', table_name='match_odds', schema='football-data')
    op.drop_index('ix_match_odds_url', table_name='match_odds', schema='football-data')
    op.drop_index('ix_match_odds_bookmaker', table_name='match_odds', schema='football-data')
    op.drop_table('match_odds', schema='football-data')
    op.drop_index('uq_match_asian_handicap', table_name='match_asian_handicap', schema='football-data')
    op.drop_index('ix_match_asian_handicap_url', table_name='match_asian_handicap', schema='football-data')
    op.drop_index('ix_match_asian_handicap_bookmaker', table_name='match_asian_handicap', schema='football-data')
    op.drop_table('match_asian_handicap', schema='football-data')
    op.drop_table('bookmaker', schema='football-data')
    # ### end Alembic commands ###
