"""Add last modified and loaded timestamps

Revision ID: 0a52641db111
Revises: 070e958c019b
Create Date: 2022-03-27 22:07:06.485538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a52641db111'
down_revision = 'c8a2799837ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('last_modified', sa.DateTime(), nullable=True), schema='football-data')
    op.add_column('season', sa.Column('last_loaded', sa.DateTime(), nullable=True), schema='football-data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('season', 'last_loaded', schema='football-data')
    op.drop_column('season', 'last_modified', schema='football-data')
    # ### end Alembic commands ###
