"""Add countries, leagues and seasons

Revision ID: 070e958c019b
Revises: 6d8a0adb672f
Create Date: 2022-03-18 15:10:54.931981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070e958c019b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'country',
        sa.Column('country_code', sa.String(length=3), nullable=False),
        sa.Column('country_name', sa.String(length=20), nullable=False),
        sa.Column('url', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('country_code', name='pk_country'),
        sa.UniqueConstraint('country_name', name='uq_country_name'),
        sa.UniqueConstraint('url', name='uq_country_url'),
        schema='football-data'
    )
    op.create_table(
        'league',
        sa.Column('division', sa.String(length=3), nullable=False),
        sa.Column('league_name', sa.String(length=100), nullable=False),
        sa.Column('country_code', sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint('division', name='pk_league'),
        sa.ForeignKeyConstraint(['country_code'], ['football-data.country.country_code'], name='fk_league_country'),
        schema='football-data'
    )
    op.create_index('uq_league', 'league', ['country_code', 'league_name'], unique=True, schema='football-data')
    op.create_table(
        'season',
        sa.Column('url', sa.String(length=100), nullable=False),
        sa.Column('division', sa.String(length=3), nullable=False),
        sa.Column('season_name', sa.String(length=20), nullable=False),
        sa.Column('last_modified', sa.DateTime(), nullable=True),
        sa.Column('last_loaded', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('url', name='pk_season'),
        sa.ForeignKeyConstraint(['division'], ['football-data.league.division'], name='fk_season_league'),
        schema='football-data'
    )
    op.create_index('uq_season', 'season', ['division', 'season_name'], unique=True, schema='football-data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_season', table_name='season', schema='football-data')
    op.drop_table('season', schema='football-data')
    op.drop_index('uq_league', table_name='league', schema='football-data')
    op.drop_table('league', schema='football-data')
    op.drop_table('country', schema='football-data')
    # ### end Alembic commands ###
